# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Alessandro Ottaviano <aottaviano@iis.ee.ethz.ch>

name: gitlab-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check Gitlab CI
        uses: pulp-platform/pulp-actions/gitlab-ci@v2.5.0 # update version as needed, not autoupdated
        # Skip on forks or pull requests from forks due to missing secrets.
        if: github.repository == 'pulp-platform/carfield' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        with:
          domain: iis-git.ee.ethz.ch
          repo: github-mirror/carfield
          token: ${{ secrets.GITLAB_TOKEN }}
          poll-count: 2160
